services:  
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - ./web:/usr/src/web/
      - logs:/usr/src/logs
    ports:
      - 8000:8000
    env_file:
      - docker/env/.env
    restart: unless-stopped

volumes:
  logs: